/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * nwshwn.java
 *
 * Created on Nov 13, 2015, 12:20:24 PM
 */

package Cinemas;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author CROSSFIRE
 */
public class nwshwn extends javax.swing.JFrame {

    /** Creates new form nwshwn */
    public nwshwn() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        insBN = new javax.swing.JButton();
        clrBN = new javax.swing.JButton();
        loadBN = new javax.swing.JButton();
        remBN = new javax.swing.JButton();
        exitBN = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        srchBN = new javax.swing.JButton();
        updBN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("NOW SHOWING");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sno", "Movie", "Genre", "Release Date", "Rating(out of 10)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Byte.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setText("Movie");

        jLabel3.setText("Genre");

        jLabel4.setText("Release date");

        jLabel5.setText("Rating");

        insBN.setText("INSERT");
        insBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insBNActionPerformed(evt);
            }
        });

        clrBN.setText("CLEAR");
        clrBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clrBNActionPerformed(evt);
            }
        });

        loadBN.setText("LOAD ");
        loadBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadBNActionPerformed(evt);
            }
        });

        remBN.setText("REMOVE");
        remBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remBNActionPerformed(evt);
            }
        });

        exitBN.setText("EXIT");
        exitBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBNActionPerformed(evt);
            }
        });

        jLabel6.setText("Sno");

        srchBN.setText("SEARCH");
        srchBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srchBNActionPerformed(evt);
            }
        });

        updBN.setText("UPDATE");
        updBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updBNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addComponent(jLabel1)
                .addContainerGap(338, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField5)
                    .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                    .addComponent(jTextField1)
                    .addComponent(jTextField3)
                    .addComponent(jTextField4))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(exitBN))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(loadBN)
                                .addGap(40, 40, 40)
                                .addComponent(insBN))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(srchBN)
                                    .addComponent(updBN))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(clrBN)
                                    .addComponent(remBN))))
                        .addContainerGap(174, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(insBN)
                            .addComponent(loadBN))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(srchBN)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(updBN))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(remBN)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(clrBN)))
                        .addGap(18, 18, 18)
                        .addComponent(exitBN))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)
                                .addGap(16, 16, 16)
                                .addComponent(jLabel3)
                                .addGap(13, 13, 13)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadBNActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
        try{
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/movies","root","1234");
            Statement stmt = con.createStatement();
            String query = "SELECT * FROM nwshwn;";
            ResultSet rs = stmt.executeQuery(query);
            while(rs.next()){
                int Sno= rs.getInt("Sno");
                String movie = rs.getString("movie");
                String genre = rs.getString("genre");
                Date reldt =rs.getDate("ReleaseDt");
                int rating= rs.getInt("Rating");
                model.addRow(new Object[]{Sno,movie,genre,reldt,rating});
            }
            rs.close();
      stmt.close();
      con.close();
   }catch(Exception e){
       JOptionPane.showMessageDialog(null,"ERROR IN CONNECTIVITY");
        }
        clrBN.setEnabled(true);
         loadBN.setEnabled(true);
          remBN.setEnabled(true);

}//GEN-LAST:event_loadBNActionPerformed

    private void exitBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBNActionPerformed
System.exit(0);        // TODO add your handling code here:
}//GEN-LAST:event_exitBNActionPerformed

    private void remBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remBNActionPerformed
        // TODO add your handling code here:
        int answer = JOptionPane.showConfirmDialog(null,"Are you sure to delete the record ?");
        if(answer == JOptionPane.YES_OPTION)
        {
            try{
                Class.forName("java.sql.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/movies","root","1234");
                Statement stmt = con.createStatement();
                String query ="delete from nwshwn where sno=("+jTextField1.getText()+";";
                stmt.executeQuery(query);
                JOptionPane.showMessageDialog(null,"RECORD DELETED FROM TABLE");
                stmt.close();
                con.close();

            }catch(Exception e){
                 JOptionPane.showMessageDialog(null,"ERROR IN CONNECTIVITY");
            }
        }
}//GEN-LAST:event_remBNActionPerformed

    private void insBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insBNActionPerformed
        // TODO add your handling code here:
        int answer = JOptionPane.showConfirmDialog(null,"Are you sure to add a new record ?");
        if(answer == JOptionPane.YES_OPTION)
        {
            try{
                Class.forName("java.sql.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/movies","root","1234");
                Statement stmt = con.createStatement();
                String query ="INSERT INTO nwshwn VALUES("+jTextField1.getText()+","+jTextField2.getText()+"','"+jTextField3.getText()+"','"+jTextField4.getText()+",'"+jTextField5.getText()+"';";
                stmt.executeQuery(query);
                JOptionPane.showMessageDialog(null,"RECORD INSERTED TO TABLE");
                stmt.close();
                con.close();

            }catch(Exception e){
                 JOptionPane.showMessageDialog(null,"ERROR IN CONNECTIVITY");
            }
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField5.setText("");
            }
}//GEN-LAST:event_insBNActionPerformed

    private void clrBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clrBNActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
        int rows=model.getRowCount();
        if(rows>0)
        {for(int i=0;i<rows;++i)
             model.removeRow(0);
        }
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField5.setText("");
}//GEN-LAST:event_clrBNActionPerformed

    private void srchBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srchBNActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
        try{
            int c=0;
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/movies","root","1234");
            Statement stmt = con.createStatement();
            String query = "SELECT * FROM nwshwn where sno="+jTextField1.getText()+";";
            ResultSet rs = stmt.executeQuery(query);
            while(rs.next()){
                int Sno= rs.getInt("Sno");
                String movie = rs.getString("movie");
                String genre = rs.getString("genre");
                Date reldt =rs.getDate("ReleaseDt");
                int rating= rs.getInt("Rating");
                model.addRow(new Object[]{Sno,movie,genre,reldt,rating});
                c=1;
            }
            if (c==0)
                JOptionPane.showMessageDialog(null,"RECORD NOT FOUND");
            rs.close();
      stmt.close();
      con.close();
   }catch(Exception e){
       JOptionPane.showMessageDialog(null,"ERROR IN CONNECTIVITY");
        }
}//GEN-LAST:event_srchBNActionPerformed

    private void updBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updBNActionPerformed
        // TODO add your handling code here:
        int answer = JOptionPane.showConfirmDialog(null,"Are you sure to update the record ?");
        if(answer == JOptionPane.YES_OPTION)
        {
            try{
                Class.forName("java.sql.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/movies","root","1234");
                Statement stmt = con.createStatement();
                String query ="UPDATE nwshwn SET SNO=("+jTextField1.getText()+",'"+jTextField2.getText()+"','"+jTextField3.getText()+"','"+jTextField4.getText()+",'"+jTextField5.getText()+"';";
                stmt.executeUpdate(query);
                JOptionPane.showMessageDialog(null,"RECORD INSERTED TO TABLE");
                stmt.close();
                con.close();

            }catch(Exception e){
                 JOptionPane.showMessageDialog(null,"ERROR IN CONNECTIVITY");
            }
            jTextField1.setText("");
            jTextField1.setText("");
            jTextField1.setText("");
            jTextField1.setText("");
            jTextField1.setText("");
            jTextField1.setText("");
        }
    }//GEN-LAST:event_updBNActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new nwshwn().setVisible(true);
                Connection con=null;
                Statement stmt=null;
                ResultSet rs=null;}
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clrBN;
    private javax.swing.JButton exitBN;
    private javax.swing.JButton insBN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JButton loadBN;
    private javax.swing.JButton remBN;
    private javax.swing.JButton srchBN;
    private javax.swing.JButton updBN;
    // End of variables declaration//GEN-END:variables

}
