package Cinemas;

import javax.swing.JOptionPane;



/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Welcome.java
 *
 * Created on 09-Jan-2015, 17:27:08
 */

/**
 *
 * @author Owner
 */
public class Welcome extends javax.swing.JFrame {

    /** Creates new form Welcome */
    public Welcome() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Alert1 = new javax.swing.JDialog();
        AGL = new javax.swing.JLabel();
        WSL = new javax.swing.JLabel();
        PBN = new javax.swing.JButton();
        Alert2 = new javax.swing.JDialog();
        UAL = new javax.swing.JLabel();
        SBL = new javax.swing.JLabel();
        CBN = new javax.swing.JButton();
        Calculator = new javax.swing.JFrame();
        CTL = new javax.swing.JLabel();
        SLL = new javax.swing.JLabel();
        ELL = new javax.swing.JLabel();
        FNTF = new javax.swing.JTextField();
        SNTF = new javax.swing.JTextField();
        RTF = new javax.swing.JTextField();
        PlusBN = new javax.swing.JButton();
        MinusBN = new javax.swing.JButton();
        MulBN = new javax.swing.JButton();
        DivBN = new javax.swing.JButton();
        ModBN = new javax.swing.JButton();
        HTL = new javax.swing.JLabel();
        ULL = new javax.swing.JLabel();
        PLL = new javax.swing.JLabel();
        CLL = new javax.swing.JLabel();
        UTF = new javax.swing.JTextField();
        PF1 = new javax.swing.JPasswordField();
        ABN = new javax.swing.JButton();

        Alert1.setTitle("Access Granted"); // NOI18N
        Alert1.setMinimumSize(new java.awt.Dimension(299, 173));

        AGL.setFont(new java.awt.Font("David", 0, 24));
        AGL.setText("Access Granted!"); // NOI18N

        WSL.setFont(new java.awt.Font("David", 0, 24));
        WSL.setText("Welcome $!r"); // NOI18N

        PBN.setFont(new java.awt.Font("Viner Hand ITC", 0, 14));
        PBN.setText("PROCEED"); // NOI18N
        PBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PBNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Alert1Layout = new javax.swing.GroupLayout(Alert1.getContentPane());
        Alert1.getContentPane().setLayout(Alert1Layout);
        Alert1Layout.setHorizontalGroup(
            Alert1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Alert1Layout.createSequentialGroup()
                .addGroup(Alert1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Alert1Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(Alert1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Alert1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(WSL))
                            .addComponent(AGL)))
                    .addGroup(Alert1Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(PBN)))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        Alert1Layout.setVerticalGroup(
            Alert1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Alert1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(AGL, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(WSL, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(PBN)
                .addGap(22, 22, 22))
        );

        Alert2.setTitle("Unauthorized Access!"); // NOI18N
        Alert2.setMinimumSize(new java.awt.Dimension(315, 169));

        UAL.setFont(new java.awt.Font("Viner Hand ITC", 0, 24));
        UAL.setText("Unauthorized Access!"); // NOI18N

        SBL.setFont(new java.awt.Font("Viner Hand ITC", 0, 24));
        SBL.setText("System Breach Activated!"); // NOI18N

        CBN.setFont(new java.awt.Font("Viner Hand ITC", 0, 18));
        CBN.setText("Cancel"); // NOI18N
        CBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Alert2Layout = new javax.swing.GroupLayout(Alert2.getContentPane());
        Alert2.getContentPane().setLayout(Alert2Layout);
        Alert2Layout.setHorizontalGroup(
            Alert2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Alert2Layout.createSequentialGroup()
                .addGroup(Alert2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Alert2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(SBL))
                    .addGroup(Alert2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(UAL))
                    .addGroup(Alert2Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(CBN)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Alert2Layout.setVerticalGroup(
            Alert2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Alert2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(UAL, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SBL, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CBN)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        Calculator.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        Calculator.setTitle("Arithmetic Calculator"); // NOI18N
        Calculator.setMinimumSize(new java.awt.Dimension(309, 207));
        Calculator.setName("CalcFrame"); // NOI18N

        CTL.setFont(new java.awt.Font("Tahoma", 1, 18));
        CTL.setText("Arithmetic Calculator"); // NOI18N

        SLL.setFont(new java.awt.Font("Tahoma", 1, 18));

        ELL.setFont(new java.awt.Font("Tahoma", 1, 18));
        ELL.setText("="); // NOI18N

        FNTF.setFont(new java.awt.Font("Tahoma", 1, 12));
        FNTF.setText(" "); // NOI18N

        SNTF.setFont(new java.awt.Font("Tahoma", 1, 12));

        RTF.setFont(new java.awt.Font("Tahoma", 1, 12));

        PlusBN.setFont(new java.awt.Font("Tahoma", 1, 12));
        PlusBN.setText("+"); // NOI18N
        PlusBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlusBNActionPerformed(evt);
            }
        });

        MinusBN.setFont(new java.awt.Font("Tahoma", 1, 12));
        MinusBN.setText("-"); // NOI18N
        MinusBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinusBNActionPerformed(evt);
            }
        });

        MulBN.setFont(new java.awt.Font("Tahoma", 1, 12));
        MulBN.setText("*"); // NOI18N
        MulBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MulBNActionPerformed(evt);
            }
        });

        DivBN.setFont(new java.awt.Font("Tahoma", 1, 12));
        DivBN.setText("/"); // NOI18N
        DivBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DivBNActionPerformed(evt);
            }
        });

        ModBN.setFont(new java.awt.Font("Tahoma", 1, 12));
        ModBN.setText("%"); // NOI18N
        ModBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModBNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CalculatorLayout = new javax.swing.GroupLayout(Calculator.getContentPane());
        Calculator.getContentPane().setLayout(CalculatorLayout);
        CalculatorLayout.setHorizontalGroup(
            CalculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CalculatorLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(CalculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(CalculatorLayout.createSequentialGroup()
                        .addComponent(PlusBN, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MinusBN, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MulBN, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DivBN, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ModBN, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CalculatorLayout.createSequentialGroup()
                        .addComponent(FNTF, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SLL, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SNTF, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(ELL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RTF)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CalculatorLayout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(CTL, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );
        CalculatorLayout.setVerticalGroup(
            CalculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CalculatorLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(CTL, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(CalculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FNTF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SNTF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ELL)
                    .addComponent(RTF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SLL, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(CalculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CalculatorLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(PlusBN, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))
                    .addGroup(CalculatorLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(MinusBN, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))
                    .addGroup(CalculatorLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(MulBN, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))
                    .addGroup(CalculatorLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(DivBN, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))
                    .addGroup(CalculatorLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(ModBN, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SSApp"); // NOI18N
        setName("WelcFrame"); // NOI18N
        setResizable(false);

        HTL.setFont(new java.awt.Font("FrankRuehl", 0, 22));
        HTL.setText("Welcome To S.A.M. Cinema"); // NOI18N

        ULL.setFont(new java.awt.Font("SimSun", 2, 18));
        ULL.setText("User ID"); // NOI18N

        PLL.setFont(new java.awt.Font("SimSun", 2, 18));
        PLL.setText("Password"); // NOI18N

        CLL.setFont(new java.awt.Font("Jokerman", 0, 11));
        CLL.setText("Caution: Unauthorized access activates system breach."); // NOI18N

        UTF.setFont(new java.awt.Font("SimSun", 0, 18));

        PF1.setFont(new java.awt.Font("SimSun", 0, 10));

        ABN.setFont(new java.awt.Font("SimSun", 2, 18));
        ABN.setText("Authorize"); // NOI18N
        ABN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ABNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CLL)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ULL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PLL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PF1, 0, 0, Short.MAX_VALUE)
                            .addComponent(ABN, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UTF, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE))))
                .addGap(25, 25, 25))
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(HTL)
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(HTL, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ULL)
                    .addComponent(UTF, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PLL, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PF1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ABN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1)
                .addComponent(CLL, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ABNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ABNActionPerformed
        // TODO add your handling code here:
        String pwd = new String(PF1.getPassword());
        String name = ULL.getText();
        if (pwd.equals("zxc"))
        {this.setVisible(false);
         new Home().setVisible(true);
         JOptionPane.showMessageDialog(this,"login succesfull");
        }
        else
            JOptionPane.showMessageDialog(this,"login unsuccesfull");
}//GEN-LAST:event_ABNActionPerformed

    private void PlusBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlusBNActionPerformed
        // TODO add your handling code here:
        SLL.setText("+");
        final double num1 = Double.parseDouble(FNTF.getText());
        final double num2 = Double.parseDouble(SNTF.getText());
        double num3 = num1 + num2;
        RTF.setText(""+num3);
}//GEN-LAST:event_PlusBNActionPerformed

    private void MinusBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinusBNActionPerformed
        // TODO add your handling code here:
        SLL.setText("-");
        final double num1 = Double.parseDouble(FNTF.getText());
        final double num2 = Double.parseDouble(SNTF.getText());
        double num3 = num1 - num2;
        RTF.setText(""+num3);
}//GEN-LAST:event_MinusBNActionPerformed

    private void MulBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MulBNActionPerformed
        // TODO add your handling code here:.
        SLL.setText("*");
        final double num1 = Double.parseDouble(FNTF.getText());
        final double num2 = Double.parseDouble(SNTF.getText());
        double num3 = num1 * num2;
        RTF.setText(""+num3);
}//GEN-LAST:event_MulBNActionPerformed

    private void DivBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DivBNActionPerformed
        SLL.setText("/");
        double num1 = Double.parseDouble(FNTF.getText());
        double num2 = Double.parseDouble(SNTF.getText());
        double num3 = num1 / num2;
        RTF.setText(""+num3);        // TODO add your handling code here:
}//GEN-LAST:event_DivBNActionPerformed

    private void ModBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModBNActionPerformed
        SLL.setText("%");
        double num1 = Double.parseDouble(FNTF.getText());
        double num2 = Double.parseDouble(SNTF.getText());
        double num3 = num1 % num2;
        RTF.setText(""+num3);        // TODO add your handling code here:
}//GEN-LAST:event_ModBNActionPerformed

    private void PBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PBNActionPerformed
        // TODO add your handling code here:
        Calculator.setVisible(true);
        Alert1.setVisible(false);
    }//GEN-LAST:event_PBNActionPerformed

    private void CBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBNActionPerformed
        // TODO add your handling code here:
        Alert2.setVisible(false);
}//GEN-LAST:event_CBNActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Welcome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ABN;
    private javax.swing.JLabel AGL;
    private javax.swing.JDialog Alert1;
    private javax.swing.JDialog Alert2;
    private javax.swing.JButton CBN;
    private javax.swing.JLabel CLL;
    private javax.swing.JLabel CTL;
    private javax.swing.JFrame Calculator;
    private javax.swing.JButton DivBN;
    private javax.swing.JLabel ELL;
    private javax.swing.JTextField FNTF;
    private javax.swing.JLabel HTL;
    private javax.swing.JButton MinusBN;
    private javax.swing.JButton ModBN;
    private javax.swing.JButton MulBN;
    private javax.swing.JButton PBN;
    private javax.swing.JPasswordField PF1;
    private javax.swing.JLabel PLL;
    private javax.swing.JButton PlusBN;
    private javax.swing.JTextField RTF;
    private javax.swing.JLabel SBL;
    private javax.swing.JLabel SLL;
    private javax.swing.JTextField SNTF;
    private javax.swing.JLabel UAL;
    private javax.swing.JLabel ULL;
    private javax.swing.JTextField UTF;
    private javax.swing.JLabel WSL;
    // End of variables declaration//GEN-END:variables

}
